namespace ITCafe.Api.Dtos.Tickets;

public record TicketDto(
    int Id,
    DateTime CreatedAt,
    DateTime? ClosedAt,
    string Assignee,
    string[] Assignees,
    string Title,
    string ClientName,
    string Problem,
    string Status,
    string Priority,
    string Department,
    string RequestType,
    string ObjectName,
    int? ObjectId,
    int ClientId,
    int? OkdeskId = null,
    string CoordinatorBriefJson = "",
    bool IsRepair = false,
    int? EquipmentId = null,
    string RepairType = "",
    decimal? RepairCost = null,
    string RepairClientName = "",
    string RepairEquipmentName = "",
    string RepairSerialNumber = "",
    string RepairLocation = "",
    string RepairFaults = "",
    string RepairNotes = "",
    string RepairFundStatus = "",
    string RepairEquipmentType = "",
    string TaskLinksJson = "",
    string AlternativeTitle = "",
    string CreatedByRole = "",
    string DelegatedFrom = "",
    string DelegatedTo = "",
    string DelegationReason = "",
    DateTime? DelegatedAt = null,
    string[]? AssigneeIds = null,
    int SubtaskCount = 0,
    string[]? BriefKnowledgeableUserIds = null,
    string[]? CommentTexts = null,
    string[]? TaskLinkUrls = null,
    bool IsFromOkdesk = false,
    bool HasUnread = false
);
